# Configuracion de Base de Datos
# Editar este archivo si usa credenciales diferentes a las predeterminadas de PostgreSQL
db.url=jdbc:postgresql://localhost:5432/skyairline_db
db.user=postgres
db.password=postgres
db.driver=org.postgresql.Driver
